apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: oqtlnulhu-python 
  janus-idp.io/tekton: oqtlnulhu-python
  backstage.io/kubernetes-id: oqtlnulhu-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oqtlnulhu-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml