apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oqtlnulhu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oqtlnulhu-python 
  name: oqtlnulhu-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oqtlnulhu-python 
